### ISSUE TITLE
System.Security.Cryptography.CryptographicException: Invalid provider type specified

### ISSUE THREAD

**Issue by carlosvasquezOF** [miguelhuertas/efacturacion-colombia-firma#7]
En el momento en que ejecuto el proceso de firmado, me aparece el siguiente error :

System.Security.Cryptography.CryptographicException: Invalid provider type specified.

   at System.Security.Cryptography.Utils.CreateProvHandle(CspParameters parameters, Boolean randomKeyContainer)
   at System.Security.Cryptography.Utils.GetKeyPairHelper(CspAlgorithmType keyType, CspParameters parameters, Boolean randomKeyContainer, Int32 dwKeySize, SafeProvHandle& safeProvHandle, SafeKeyHandle& safeKeyHandle)
   at System.Security.Cryptography.RSACryptoServiceProvider.GetKeyPair()
   at System.Security.Cryptography.RSACryptoServiceProvider..ctor(Int32 dwKeySize, CspParameters parameters, Boolean useDefaultKeySize)
   at System.Security.Cryptography.X509Certificates.X509Certificate2.get_PrivateKey()
   at FirmaXades.Crypto.Signer.SetSigningKey(X509Certificate2 certificate)
   at FirmaXades.Crypto.Signer..ctor(X509Certificate2 certificate)
   at eFacturacionColombia.Firma.FirmaElectronica._firmar(Byte[] _bytesXml, TipoDocumento _tipo, DateTime _fecha)
   at eFacturacionColombia.Firma.FirmaElectronica.Firmar(String _contenidoXml, TipoDocumento _tipo, DateTime _fecha)

Pero unicamente cuando se ejecuta en release, en debug no aparece el error

**Comment by miguelhuertas** [comment]
Hola @carlosvasquezOF 
Eso pasa cuando publicas tu aplicación en el servidor, no?
Configura el **Identity** del _app pool_ (de tu aplicación web) en **LocalSystem**

**Comment by felipe-xx** [comment]
Hola Miguel, estoy tratando de usar tu aplicación pero me responde con un error:
Unable to cast object of type 'System.Security.Cryptography.RSACng' to type 'System.Security.Cryptography.RSACryptoServiceProvider'.
System.Collections.ListDictionaryInternal

No se a que se debe esto y cual podría ser la solución.
Gracias
